#!/usr/bin/env python3
"""
Workflow 2: Post-Meeting Minutes Distribution
Triggered manually by Luan after each meeting ends.
Pulls HappyScribe transcript, corrects names, summarizes, fills minutes, emails team.
"""

import os
import sys
import json
from datetime import datetime, date

from config import PROJECTS
from roster import correct_transcript_names, get_project_members, download_workbook
from happyscribe import find_todays_transcripts, export_transcript_text, match_transcript_to_project
from send_email import send_minutes_email

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), 'output')


def find_project_by_name(name):
    """Find a project config by name or short name (case-insensitive)."""
    name_lower = name.lower()
    for p in PROJECTS:
        if name_lower in p['name'].lower() or name_lower in p['short_name'].lower():
            return p
    return None


def summarize_transcript(transcript_text, project_name):
    """
    Generate a structured summary from the transcript.
    Returns a dict with topics, decisions, action_items, blockers.
    """
    lines = transcript_text.strip().split('\n')
    non_empty = [l.strip() for l in lines if l.strip()]

    summary = {
        'topics': [],
        'decisions': [],
        'action_items': [],
        'blockers': [],
        'raw_text': transcript_text,
    }

    current_speaker = None
    current_text = []

    for line in non_empty:
        if ':' in line and not line.startswith(' '):
            parts = line.split(':', 1)
            if len(parts[0].split()) <= 3:
                if current_speaker and current_text:
                    text = ' '.join(current_text)
                    lower = text.lower()
                    if any(kw in lower for kw in ['decided', 'agreed', 'confirmed', 'approved', 'we will']):
                        summary['decisions'].append(f'{current_speaker}: {text}')
                    if any(kw in lower for kw in ['action', 'todo', 'will do', 'i will', 'need to', 'should', 'assigned']):
                        summary['action_items'].append(f'{current_speaker}: {text}')
                    if any(kw in lower for kw in ['blocked', 'blocker', 'stuck', 'issue', 'problem', 'challenge']):
                        summary['blockers'].append(f'{current_speaker}: {text}')
                current_speaker = parts[0].strip()
                current_text = [parts[1].strip()] if len(parts) > 1 else []
            else:
                current_text.append(line)
        else:
            current_text.append(line)

    if current_speaker and current_text:
        text = ' '.join(current_text)
        lower = text.lower()
        if any(kw in lower for kw in ['decided', 'agreed', 'confirmed']):
            summary['decisions'].append(f'{current_speaker}: {text}')
        if any(kw in lower for kw in ['action', 'todo', 'will do', 'i will', 'need to']):
            summary['action_items'].append(f'{current_speaker}: {text}')
        if any(kw in lower for kw in ['blocked', 'blocker', 'stuck', 'issue']):
            summary['blockers'].append(f'{current_speaker}: {text}')

    return summary


def format_minutes_body(summary, project_name, meeting_date_str):
    """Format the summary into a clean email body."""
    lines = [
        f'{project_name} — Meeting Minutes [{meeting_date_str}]',
        '',
        '=' * 60,
        '',
    ]

    if summary['decisions']:
        lines.append('KEY DECISIONS:')
        for i, d in enumerate(summary['decisions'], 1):
            lines.append(f'  {i}. {d}')
        lines.append('')

    if summary['action_items']:
        lines.append('ACTION ITEMS:')
        for i, a in enumerate(summary['action_items'], 1):
            lines.append(f'  {i}. {a}')
        lines.append('')

    if summary['blockers']:
        lines.append('BLOCKERS / ISSUES:')
        for i, b in enumerate(summary['blockers'], 1):
            lines.append(f'  {i}. {b}')
        lines.append('')

    lines.extend([
        '=' * 60,
        '',
        'FULL TRANSCRIPT SUMMARY:',
        '',
    ])

    transcript_lines = summary['raw_text'].split('\n')
    if len(transcript_lines) > 100:
        lines.extend(transcript_lines[:100])
        lines.append(f'\n... [{len(transcript_lines) - 100} more lines in full transcript]')
    else:
        lines.extend(transcript_lines)

    lines.extend([
        '',
        '---',
        'Generated by Sparky — Intrastack Meeting Automation',
    ])

    return '\n'.join(lines)


def process_meeting(project_name, transcript_id=None, meeting_date=None):
    """Process a single project's meeting: pull transcript, correct names, summarize, email."""
    if meeting_date is None:
        meeting_date = date.today()

    date_str = meeting_date.strftime('%m.%d.%Y')

    project = find_project_by_name(project_name)
    if not project:
        print(f'Project not found: {project_name}')
        return False

    print(f'\n=== Processing: {project["name"]} ===\n')

    # Step 1: Get transcript
    if transcript_id:
        print(f'Using provided transcript ID: {transcript_id}')
        transcript_text = export_transcript_text(transcript_id)
    else:
        print('Searching for today\'s transcripts...')
        transcripts = find_todays_transcripts(meeting_date)
        matched = match_transcript_to_project(
            {'name': project_name}, PROJECTS
        )

        project_transcripts = []
        for t in transcripts:
            match = match_transcript_to_project(t, [project])
            if match:
                project_transcripts.append(t)

        if not project_transcripts:
            print(f'No transcript found for {project["name"]} on {meeting_date}')
            print(f'Available transcripts: {[t.get("name", "?") for t in transcripts]}')
            return False

        latest = project_transcripts[-1]
        print(f'Found transcript: {latest.get("name", "?")}')
        transcript_text = export_transcript_text(latest['id'])

    # Step 2: Correct names
    print('Correcting names against roster...')
    corrected_text, corrections = correct_transcript_names(transcript_text, project['name'])

    # Step 3: Summarize
    print('Generating summary...')
    summary = summarize_transcript(corrected_text, project['name'])

    # Step 4: Format and send email
    body = format_minutes_body(summary, project['name'], date_str)

    print(f'Sending minutes to {len(project["emails"])} recipients...')
    success = send_minutes_email(
        to_emails=project['emails'],
        project_name=project['name'],
        date_str=date_str,
        body_text=body,
    )

    return success


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print('Usage: python workflow_postmeeting.py "Project Name" [transcript_id] [YYYY-MM-DD]')
        sys.exit(1)

    project = sys.argv[1]
    tid = sys.argv[2] if len(sys.argv) > 2 else None
    mdate = datetime.strptime(sys.argv[3], '%Y-%m-%d').date() if len(sys.argv) > 3 else None

    process_meeting(project, tid, mdate)
